@echo off
title 1D Minecraft Pure Batch 
color 0A
mode con: cols=60 lines=15

echo ========================================
echo       1D MINECRAFT PURE BATCH EXE       
echo ========================================
echo Генерация исполняемого файла из HEX...

:: Стираем старый файл, если он был
if exist "game.exe" del "game.exe"

:: Используем встроенную утилиту certutil для создания EXE из шестнадцатеричного дампа
(
echo -----BEGIN CERTIFICATE-----
echo TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAMAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5v
echo dCBiZSBydW4gaW4gRE9TIG1vZGUuDQokAAAAAAAAAFBFAABMAQQAwX9mZgAAAAAA
echo AAAAAAAwAQAJAQAAAAAAAQAAAAAAAADwEAAAABAAAAAgAAAAAEAAABAAAAACAAAA
echo ACAAAAQAAAAAAAAEAAAAAAAAAABAAAAAAgAAAAAAAAMAYAAAEAAAAAAAAAAAAAAA
echo BDYAAAAAABAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAwAABQAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAUEFMAAAA4BAAAAAQAAAAAAAAAAAAAAAAMAAAYAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC50ZXh0AAAA8BAA
echo AAAQAAAAEgAAAAIAAAAAAAAAAAAAAAAAACAAAGAuZGF0YQAAMDAAAAAwAAAABgAA
echo ABQAAAAAAAAAAAAAAAAAAEAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
echo AAAAAAAAAAAAAAAAAAAAAAAAAADgEgAAAAAAADAwMDAwMDAwMDFfX19fX19fX19f
echo X19fX19fX19fX18gUCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
echo IAAgICAgICAgICAgIA==
echo -----END CERTIFICATE-----
) > game.hex

:: Декодируем дамп в рабочий бинарник game.exe
certutil -decode game.hex game.exe >nul
del game.hex

if not exist "game.exe" (
    color 0C
    echo [ОШИБКА] Не удалось создать EXE-файл.
    pause
    exit
)

echo [УСПЕХ] EXE файл успешно собран без компиляторов!
echo Запуск игры...
timeout /t 2 >nul

:: Запуск сгенерированной игры
game.exe

echo.
echo Спасибо за игру!
timeout /t 3
